---
# ==============================================================================
# site-ha-targeted-compose.yml
# ==============================================================================
# PURPOSE  : Deploy Solace PubSub+ via rootless podman-compose under a
#            systemd --user unit in a 3-node HA configuration.
#
# This playbook is PARALLEL to site-ha-targeted.yml (the podman run path).
# The podman run path is UNCHANGED and remains the default.
# Selecting this playbook OR setting broker_runtime=podman_compose in
# group_vars/all.yml switches the deployment mechanism.  Both paths share:
#   - the same inventory, group_vars, HA topology, and broker names
#   - the same pre-req / hardening roles (solace_assertion_target,
#     solace_podman_graphroot_maintenance, solace_folders_podman_unshare,
#     solace_podman_repo_policy, solace_secrets_*, solace_scripts_*)
#
# ROLLBACK: revert to podman run by running site-ha-targeted.yml.
#   The compose unit will be displaced by the podman run systemd unit.
#
# MANUAL STEPS (not automated here — owner: operator):
#   1. Vault vars: admin_pwd, broker.redundancy_authentication_presharedkey_key
#      Generate preshared key: openssl rand -base64 33
#   2. TLS server certificate — needed only when client TLS ports are exposed.
#      Until then, the broker runs SEMP on 443/1943 with a self-signed cert
#      generated by solace_secrets_certs.
#   3. Firewall approval — solace_ha_ports (8300-8302/tcp+udp, 8741, 55555)
#      and solace_client_ports must be approved and opened between the 3 nodes.
#   4. Cross-site DR replication (:55443 replication endpoints) is OUT OF SCOPE
#      for this local 3-node HA group. Do not fold into the matelink config.
#   5. Run against VM2 (ha_backup_node) FIRST to prove the automation before
#      touching VM3 / VM1 (primary).
#
# Usage:
#   ansible-playbook site-ha-targeted-compose.yml \
#     -i inventories/nonp/cn/cdc-dev1 \
#     --user solace -T 60 \
#     -e "admin_pwd=<vault> applicable_host=ha_backup_node"
#
# First clean HA bring-up (wipes storage — use once on empty VMs):
#   ansible-playbook site-ha-targeted-compose.yml \
#     -i inventories/nonp/cn/cdc-dev1 \
#     --user solace -T 60 \
#     -e "admin_pwd=<vault> solace_force_reinit=true applicable_host=ha_servers"
# ==============================================================================

# ── Phase 0: validate preconditions ──────────────────────────────────────────
- name: Fail if admin_pwd is unset, empty, or an unsubstituted placeholder
  hosts: "{{ override_host | default( applicable_host | default('ha_servers') ) }}"
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Assert admin_pwd is set
      ansible.builtin.assert:
        that:
          - admin_pwd is defined
          - admin_pwd | length > 0
          - not admin_pwd is match('^\$\[\[.*\]\]$')
        fail_msg: "admin_pwd is not set or still contains a placeholder. Aborting."
        success_msg: "admin_pwd is set."

# ── Phase 1 (solace user): assertion ─────────────────────────────────────────
# PRE-REQUISITE: site-ha-targeted-admin-setup.yml must have been run once on
# fresh VMs before this playbook.  It handles:
#   - ulimits/nofile 1048576 → admin_solace_config_system_enablement
#     (/etc/security/limits.d/99-solace-ulimits.conf)
#   - user@<uid>.service.d/delegate.conf → admin_solace_config_system_enablement_post_user_creation
#   - linger + SELinux relabel → admin_config_rootless_solace_user
#   - firewall → managed at infra level (admin_security_firewall stops firewalld)
# This playbook is the DEPLOY step only — mirrors site-ha-targeted.yml exactly.
- name: "Phase 1 — Assertion on target host prerequisites"
  hosts: "{{ override_host | default( applicable_host | default('ha_servers') ) }}"
  become: true
  become_user: "{{ solace_local_service_user }}"
  gather_facts: true
  roles:
    - { role: "solace_assertion_target", tags: "solace_assertion_target" }
  any_errors_fatal: true

# ── Phase 4 (solace user): compose file + systemd unit + directories ─────────
- name: "Phase 2 — Compose setup: files, secrets, podman graphroot, unshare"
  hosts: "{{ override_host | default( applicable_host | default('ha_servers') ) }}"
  become: true
  become_user: "{{ solace_local_service_user }}"
  gather_facts: true
  roles:
    - { role: "solace_compose",                    tags: "solace_compose" }
    - { role: "solace_scripts_setup",              tags: "solace_scripts_setup" }
    - { role: "solace_secrets_certs",              tags: "solace_secrets_certs" }
    - { role: "solace_secrets_admin",              tags: "solace_secrets_admin" }
    - { role: "solace_secrets_preshared_key",      tags: "solace_secrets_preshared_key" }
    - { role: "solace_podman_graphroot_maintenance", tags: "solace_podman_graphroot_maintenance" }
    # unshare AFTER graphroot update — chowns storage-group into the container namespace
    - { role: "solace_folders_podman_unshare",     tags: "solace_folders_podman_unshare" }
    - { role: "solace_podman_repo_policy",         tags: "solace_podman_repo_policy" }

# ── Phase 5 (solace user): start ──────────────────────────────────────────────
- name: "Phase 3 — Start Solace via systemd --user (podman-compose)"
  hosts: "{{ override_host | default( applicable_host | default('ha_servers') ) }}"
  become: true
  become_user: "{{ solace_local_service_user }}"
  gather_facts: true
  roles:
    - { role: "solace_compose_start", tags: "solace_compose_start" }

# ── Phase 6 (solace user): readiness ─────────────────────────────────────────
- name: "Phase 4 — Storage status check (skip if SEMP plain is deactivated)"
  import_playbook: site-ha-targeted-execute-storage-status-check-script-and-wait.yml

- import_playbook: site-ha-targeted-setup-readiness-script.yml

- name: "Phase 4b — Node readiness (CLI path when SEMP plain is deactivated)"
  import_playbook: site-ha-targeted-execute-readiness-script-and-wait.yml
  vars:
    execute: "{{ is_semp_plain_deactivated | default(false) | bool }}"

# ── Phase 7 (solace user): configure + verify ────────────────────────────────
- name: "Phase 5 — SEMP configuration + script execution"
  hosts: "{{ override_host | default( applicable_host | default('ha_servers') ) }}"
  become: true
  become_user: "{{ solace_local_service_user }}"
  gather_facts: true
  roles:
    - { role: "solace_scripts_setup",   tags: "solace_scripts_setup",   when: "not is_semp_plain_deactivated | default(true) | bool" }
    - { role: "solace_scripts_execute", tags: "solace_scripts_execute",  when: "not is_semp_plain_deactivated | default(true) | bool" }

- name: "Phase 5b — Wait for Solace startup"
  hosts: "{{ override_host | default( applicable_host | default('ha_servers') ) }}"
  become: true
  become_user: "{{ solace_local_service_user }}"
  gather_facts: true
  roles:
    - { role: "solace_scripts_execute_wait_solace_startup", tags: "solace_scripts_execute_wait_solace_startup",
        when: "not is_semp_plain_deactivated | default(true) | bool" }

- name: "Phase 5c — Configure redundancy config-sync preshared key"
  hosts: "{{ override_host | default( applicable_host | default('ha_servers') ) }}"
  become: true
  become_user: "{{ solace_local_service_user }}"
  gather_facts: true
  roles:
    - { role: "solace_configure_replication_config_sync_preshared_key",
        tags: "solace_configure_replication_config_sync_preshared_key",
        when: "not is_semp_plain_deactivated | default(true) | bool" }

# ── Phase 8 (solace user): compose-specific verification ─────────────────────
- name: "Phase 6 — Compose verification (container, nofile, POST, SEMP)"
  hosts: "{{ override_host | default( applicable_host | default('ha_servers') ) }}"
  become: true
  become_user: "{{ solace_local_service_user }}"
  gather_facts: true
  roles:
    - { role: "solace_compose_verify", tags: "solace_compose_verify" }

# ── Phase 9: summary + security hardening ────────────────────────────────────
- name: "Phase 7 — Display summary"
  hosts: "{{ override_host | default( applicable_host | default('ha_servers') ) }}"
  become: true
  become_user: "{{ solace_local_service_user }}"
  gather_facts: true
  roles:
    - { role: "solace_summary", tags: "solace_summary" }

- import_playbook: site-ha-targeted-security-hardening-no-readiness.yml
- import_playbook: site-ha-targeted-update-healthcheck-ports.yml

